language: python
python:
- '3.6'
install: true
script: echo "Deploying Janis-Unix"
deploy:
  provider: pypi
  user: illusional
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: PMCC-BioinformaticsCore/janis-unix
  password:
    secure: ShxtrxGp27qui1JymO9dWS1W1EvAvLcTWPcpVzJ+NFtlqM0PZ8694W7nnj1W6Wc/HpR5su/Odal7ggeUomUX5q5QvDIohcUiQQcsAU082w2Ml6ZN8E7mFFM6bAY9vmECFxAvbaIBEUB5tOm+npcbkJ7weQAE6Yb1Apzay/2ytYjjXqe3juqnhSQQNg9kGHO4F13QSFtjqqmy6u0qcFD9n2Y+36UTl396Z+yVV6aQCyhx2S0Sv4LD9kfRdpq3YmlPU4YNVCc8t0+vJf2Mz+3KY78E68K7ATngXr88lWjncLbzYSZ1tlVfnVz1fX+dBaeggW1tLrs83N+9Vnit22IO4xeDI1VB9FD7+cTFhmr9ZFlfb+P8LJUIOspZMLsslYzVGpmrNR7Cb2bBR4b7wxQEphnxUI53QVKVpy6RmSUnT0fUk9NooLU4Ulfa81omARHRtw6kyCL5//qp9UVSAyJ9J8Ux80GmU4pM2rgr5neWgjfkvJhfFwz1GrfbnJiSZRY9518HraouqlsWhoOiMbUfZ81rSz4YGJzjQRQtWMl/JtPsWP9+2DRIPaayVShBmng7L8MLIngXzZSXf6UzCuJrgJ4QEM1OwUqPFFRcrT4AzduVtANrjMQpM33qFsjuKKInOlVigrsKhKu61qxYO4MA77ZR4Rk0cjBNcalzLRpVhRM=
